import os

# Map of Chinese -> English translations for all frontend files
translations = {
    # Layout / Navigation
    '首页': 'Home',
    '端点管理': 'Endpoints',
    '模型管理': 'Models',
    'API 密钥': 'API Keys',
    '用户管理': 'Users',
    '计划管理': 'Plans',
    '个人资料': 'Profile',
    '退出登录': 'Sign Out',
    '管理员': 'Admin',
    '普通用户': 'User',
    
    # Init page
    '管理员账号初始化': 'Admin Account Setup',
    '系统已初始化': 'System Initialized',
    '系统已经初始化过，正在跳转到登录页...': 'System has already been initialized. Redirecting to login...',
    '立即登录': 'Sign In Now',
    '初始化失败': 'Initialization Failed',
    '请输入用户名和密码': 'Please enter a username and password',
    '初始化失败，请稍后再试': 'Initialization failed. Please try again later.',
    '初始化系统': 'Initialize System',
    '确认密码': 'Confirm Password',
    '请再次输入密码': 'Please re-enter your password',
    '两次输入的密码不一致': 'Passwords do not match',
    '密码长度不能小于8位': 'Password must be at least 8 characters',
    '密码长度不能大于128位': 'Password must be at most 128 characters',
    
    # Login page
    '登录失败': 'Login Failed',
    '发生未知错误，请稍后重试': 'An unknown error occurred. Please try again later.',
    '登录': 'Sign In',
    
    # Common form labels
    '用户名': 'Username',
    '密码': 'Password',
    '请输入用户名': 'Enter your username',
    '请输入密码': 'Enter your password',
    
    # Settings page
    '修改密码': 'Change Password',
    '当前密码': 'Current Password',
    '新密码': 'New Password',
    '确认新密码': 'Confirm New Password',
    '请输入当前密码': 'Enter current password',
    '请输入新密码': 'Enter new password',
    '请再次输入新密码': 'Re-enter new password',
    '请填写所有密码字段': 'Please fill in all password fields',
    '新密码与确认密码不匹配': 'New password and confirmation do not match',
    '密码修改成功': 'Password Changed',
    '请使用新密码登录': 'Please sign in with your new password',
    '密码修改失败': 'Password Change Failed',
    '请检查旧密码是否正确': 'Please check if your current password is correct',
    '密码修改成功！': 'Password changed successfully!',
    '系统设置': 'System Settings',
    '设为 0 禁用自动更新': 'Set to 0 to disable auto-update',
    '更新端点任务间隔（小时）': 'Endpoint Test Interval (hours)',
    '更新端点任务间隔成功': 'Interval Updated',
    '请等待端点任务更新': 'Please wait for the endpoint tasks to update',
    '更新端点任务间隔失败': 'Interval Update Failed',
    '请检查更新端点任务间隔是否正确': 'Please check if the interval value is valid',
    '更新': 'Update',
    '账户信息': 'Account Info',
    '用户名：': 'Username:',
    '用户 ID：': 'User ID:',
    '用户类型：': 'User Type:',
    
    # Profile page
    '当前计划': 'Current Plan',
    '计划名称：': 'Plan Name:',
    '每分钟请求数限制：': 'Requests Per Minute Limit:',
    '每天请求数限制：': 'Requests Per Day Limit:',
    '计划描述：': 'Plan Description:',
    '加载计划信息失败': 'Failed to load plan info',
    
    # Not found page
    '您访问的页面不存在或已被移除。': 'The page you are looking for does not exist or has been removed.',
    '返回首页': 'Back to Home',
    
    # Unauthorized page
    '您没有权限访问此页面，此页面需要管理员权限才能访问。': 'You do not have permission to access this page. Admin privileges are required.',

    # Dashboard page
    '欢迎使用 Ollama Hack 平台，这里可以管理你的 Ollama 端点和 AI 模型。': 'Welcome to the Ollama Hack platform. Manage your Ollama endpoints and AI models here.',
    '端点': 'Endpoints',
    '已添加的端点总数': 'Total endpoints added',
    '可用端点': 'Available Endpoints',
    'AI 模型': 'AI Models',
    '扫描出的 AI 模型总数': 'Total AI models discovered',
    '可用 AI 模型': 'Available AI Models',
    '发生了一个错误': 'An error occurred',
    
    # Endpoints
    '端点列表': 'Endpoint List',
    '搜索端点...': 'Search endpoints...',
    '暂无端点数据': 'No endpoint data',
    '添加端点': 'Add Endpoint',
    '添加第一个端点': 'Add your first endpoint',
    '创建新端点': 'Create New Endpoint',
    '单个创建': 'Single',
    '批量创建': 'Batch Create',
    'URL 不能为空': 'URL cannot be empty',
    '创建端点失败': 'Failed to create endpoint',
    '请重试': 'Please try again',
    '批量创建端点失败': 'Failed to batch create endpoints',
    '请输入至少一个有效的端点 URL': 'Please enter at least one valid endpoint URL',
    '取消': 'Cancel',
    '创建': 'Create',
    '创建中...': 'Creating...',
    '编辑端点': 'Edit Endpoint',
    '端点 URL 不可修改': 'Endpoint URL cannot be modified',
    '端点 URL': 'Endpoint URL',
    '端点名称': 'Endpoint Name',
    '端点 URLs': 'Endpoint URLs',
    '名称不能为空': 'Name cannot be empty',
    '更新端点失败': 'Failed to update endpoint',
    '输入 Ollama 服务的完整 URL，包括协议和端口': 'Enter the full Ollama service URL, including protocol and port',
    '可选，如不填写将使用 URL 主机名': 'Optional. If left empty, the URL hostname will be used',
    '给端点起个名字': 'Give this endpoint a name',
    '每行输入一个 URL。如果没有指定协议，将默认使用 http://。系统会自动以主机名作为端点名称。': 'Enter one URL per line. If no protocol is specified, http:// will be used by default. Hostnames will be used as endpoint names automatically.',
    '端点信息': 'Endpoint Info',
    '名称': 'Name',
    '状态': 'Status',
    '创建时间': 'Created At',
    '操作': 'Actions',
    'Ollama 版本': 'Ollama Version',
    '最后检查时间': 'Last Checked',
    '未知': 'Unknown',
    '可用模型': 'Available Models',
    '该端点上没有可用的 AI 模型': 'No AI models available on this endpoint',
    '加载端点详情失败': 'Failed to load endpoint details',
    '未找到端点信息': 'Endpoint not found',
    '查看端点': 'View Endpoint',
    '测试端点': 'Test Endpoint',
    '删除端点': 'Delete Endpoint',
    '确定要删除这个端点吗？此操作不可撤销。': 'Are you sure you want to delete this endpoint? This action cannot be undone.',
    '删除端点失败': 'Failed to delete endpoint',
    '批量测试': 'Batch Test',
    '批量删除': 'Batch Delete',
    '批量测试已触发': 'Batch test triggered',
    '批量测试失败': 'Batch test failed',
    '批量删除成功': 'Batch delete successful',
    '批量删除失败': 'Batch delete failed',
    '确认批量测试端点': 'Confirm Batch Test',
    '确认批量删除端点': 'Confirm Batch Delete',
    '确认测试端点': 'Confirm Test Endpoint',
    '测试已触发': 'Test triggered',
    '触发测试失败': 'Failed to trigger test',
    '测试失败': 'Test Failed',
    '测试成功': 'Test Successful',
    'AI模型': 'AI Models',
    '加载端点列表失败': 'Failed to load endpoint list',
    '保存更改': 'Save Changes',
    '保存中...': 'Saving...',
    
    # Models
    '模型信息': 'Model Info',
    '模型列表': 'Model List',
    '搜索模型...': 'Search models...',
    '暂无模型数据': 'No model data',
    '查看模型': 'View Model',
    '标签': 'Tag',
    '端点数量': 'Endpoint Count',
    '可用端点数': 'Available Endpoints',
    '没有可用的端点': 'No available endpoints',
    '加载模型详情失败': 'Failed to load model details',
    '未找到模型信息': 'Model not found',
    '模型': 'Model',
    '性能': 'Performance',
    '未测试': 'Not tested',
    '不可用': 'Unavailable',
    '生成速度（每秒token数）': 'Generation speed (tokens per second)',
    
    # API Keys page
    'API 密钥列表': 'API Key List',
    '搜索 API 密钥...': 'Search API keys...',
    '暂无 API 密钥数据': 'No API key data',
    '创建 API 密钥': 'Create API Key',
    '创建第一个 API 密钥': 'Create your first API key',
    'API 密钥名称': 'API Key Name',
    '输入 API 密钥名称': 'Enter API key name',
    '密钥创建成功': 'Key Created Successfully',
    '请保存好您的 API 密钥，这是唯一可以看到它的机会：': 'Please save your API key now. This is the only time you will be able to see it:',
    '确定': 'OK',
    '确定要删除此 API 密钥吗？此操作不可逆。': 'Are you sure you want to delete this API key? This action is irreversible.',
    '删除 API 密钥失败': 'Failed to delete API key',
    '查看密钥用量': 'View Key Usage',
    '删除密钥': 'Delete Key',
    '从未使用': 'Never used',
    '使用方法': 'Usage Guide',
    '聚合 API 使用方法': 'Aggregated API Usage Guide',
    '什么是聚合 API ?': 'What is the Aggregated API?',
    '如何使用聚合 API ?': 'How to use the Aggregated API?',
    'Ollama 原生 API 文档': 'Ollama Native API Docs',
    'OpenAI 兼容 API 文档': 'OpenAI Compatible API Docs',
    '聚合 API 是 ': 'The Aggregated API is the core feature of ',
    ' 的核心功能，旨在通过一个仿\n                    Ollama 的 OpenAI 兼容 API，智能访问扫描到的高可用模型。': '.\n                    It provides smart access to discovered high-availability models through an Ollama-compatible OpenAI API.',
    '首先，你需要生成一个 API 密钥。注意，你只会在创建时看到 API\n                    密钥，生成后将无法再次查看，请妥善保管。': 'First, you need to generate an API key. Note that you will only see\n                    the API key once upon creation — it cannot be viewed again, so keep it safe.',
    'API 密钥创建': 'API Key Creation',
    '接下来你就可以使用这个 API 密钥来访问聚合 API 了。API\n                    密钥可以通过请求头传递。': 'You can now use this API key to access the Aggregated API.\n                    The API key is passed via request headers.',
    '例如，你可以这样访问聚合 API：': 'For example, you can access the Aggregated API like this:',
    '你是一个有帮助的助手': 'You are a helpful assistant',
    '你好，请介绍一下自己': 'Hello, please introduce yourself',
    '你的 API 密钥': 'your-api-key',
    'Ollama API 文档': 'Ollama API Docs',
    
    # Stats drawer
    '使用统计': 'Usage Statistics',
    '总请求数': 'Total Requests',
    '最近30天请求数': 'Last 30 Days Requests',
    '今日请求数': 'Requests Today',
    '成功率': 'Success Rate',
    '成功请求数': 'Successful Requests',
    '失败请求数': 'Failed Requests',
    '每日请求数': 'Daily Requests',
    '暂无每日请求数据': 'No daily request data',
    '加载API密钥使用统计失败': 'Failed to load API key usage stats',
    '未找到API密钥使用统计': 'API key usage stats not found',
    '成功请求占总请求的百分比': 'Percentage of successful requests out of total',
    ' 使用统计': ' Usage Stats',
    
    # Plans page
    '计划列表': 'Plan List',
    '搜索计划...': 'Search plans...',
    '暂无计划数据': 'No plan data',
    '创建计划': 'Create Plan',
    '创建第一个计划': 'Create your first plan',
    '创建新计划': 'Create New Plan',
    '计划名称': 'Plan Name',
    '输入计划名称': 'Enter plan name',
    '描述': 'Description',
    '输入计划描述': 'Enter plan description',
    '每分钟请求数 (RPM)': 'Requests Per Minute (RPM)',
    '输入每分钟请求数限制': 'Enter requests per minute limit',
    '每天请求数 (RPD)': 'Requests Per Day (RPD)',
    '输入每天请求数限制': 'Enter requests per day limit',
    '设为默认计划': 'Set as Default Plan',
    '默认计划': 'Default Plan',
    '编辑计划': 'Edit Plan',
    '保存': 'Save',
    '创建计划失败': 'Failed to create plan',
    '更新计划失败': 'Failed to update plan',
    '确定要删除此计划吗？此操作不可逆，且可能影响使用此计划的用户。': 'Are you sure you want to delete this plan? This action is irreversible and may affect users on this plan.',
    '编辑': 'Edit',
    '删除': 'Delete',
    '每分钟请求数': 'RPM',
    '每天请求数': 'RPD',
    '是': 'Yes',
    '否': 'No',
    
    # Users page
    '用户列表': 'User List',
    '搜索用户...': 'Search users...',
    '暂无用户数据': 'No user data',
    '创建用户': 'Create User',
    '创建第一个用户': 'Create your first user',
    '创建新用户': 'Create New User',
    '输入用户名': 'Enter username',
    '输入密码': 'Enter password',
    '设为管理员': 'Set as Admin',
    '创建用户失败': 'Failed to create user',
    '用户名和密码不能为空': 'Username and password cannot be empty',
    '编辑用户': 'Edit User',
    '输入新密码': 'Enter new password',
    '留空则不修改密码': 'Leave empty to keep current password',
    '关联计划': 'Associated Plan',
    '选择计划': 'Select a plan',
    '加载中...': 'Loading...',
    '更新用户成功': 'User Updated',
    '用户信息已成功更新': 'User information has been updated successfully',
    '更新用户失败': 'Failed to update user',
    '用户名不能为空': 'Username cannot be empty',
    '角色': 'Role',
    '计划': 'Plan',
    '权限不足': 'Insufficient Permissions',
    '您没有权限访问此页面': 'You do not have permission to access this page',
    '确定要删除此用户吗？此操作不可逆，且可能影响使用此用户的服务。': 'Are you sure you want to delete this user? This action is irreversible.',
    '删除用户成功': 'User Deleted',
    '用户已成功删除': 'The user has been deleted successfully',
    
    # DataTable
    '选择列': 'Columns',
    '显示的列': 'Visible Columns',
    '添加': 'Add',
    '搜索...': 'Search...',
    '预设大小': 'Preset Sizes',
    '自定义': 'Custom',
    '应用': 'Apply',
    '暂无数据': 'No data',
    '关闭': 'Close',
    '设置': 'Settings',
    
    # Misc
    '用户': 'User',
}

# Comments-only translations (for code comments)
comment_translations = {
    '// 检查系统是否已经初始化': '// Check if system is initialized',
    '// 如果成功获取用户信息，说明系统已初始化': '// If user info is retrieved, system is initialized',
    '// 自动重定向到登录页': '// Auto redirect to login page',
    '// 错误意味着系统未初始化，可以继续': '// Error means system is not initialized, proceed',
    '// 初始化成功后跳转登录': '// Redirect to login after initialization',
    '// 获取重定向来源': '// Get redirect source',
    '// 使用惰性加载导入 EndpointListPage 组件': '// Lazy load EndpointListPage component',
    '// 路由组件': '// Router component',
    '// 模型列表页面': '// Model list page',
    '// 验证配置': '// Validation config',
    '// 使用URL参数管理状态，替代多个单独的useState': '// Use URL params for state management instead of multiple useState',
    '// 详情抽屉状态': '// Detail drawer state',
    '// 获取模型列表': '// Fetch model list',
    '// 当总页数变化时，更新验证配置': '// Update validation config when total pages change',
    '// 处理搜索': '// Handle search',
    '// 处理页码变化': '// Handle page change',
    '// 打开模型详情抽屉': '// Open model detail drawer',
    '// 关闭模型详情抽屉': '// Close model detail drawer',
    '// 模型详情抽屉': '// Model detail drawer',
    '// 模型路由入口': '// Model router entry',
    '// 排序状态': '// Sort state',
    '// 处理排序': '// Handle sort',
    '// 获取 API 密钥列表': '// Fetch API key list',
    '// 搜索时重置页码': '// Reset page on search',
    '// 处理创建 API 密钥': '// Handle create API key',
    '// 处理关闭创建成功对话框': '// Handle close success dialog',
    '// 处理删除 API 密钥': '// Handle delete API key',
    '// 打开API密钥统计抽屉': '// Open API key stats drawer',
    '// 关闭API密钥统计抽屉': '// Close API key stats drawer',
    '// 定义表格列': '// Define table columns',
    '// 渲染单元格内容': '// Render cell content',
    '// 创建 API 密钥对话框': '// Create API key dialog',
    '// API密钥统计抽屉': '// API key stats drawer',
    '// 使用方法抽屉': '// Usage guide drawer',
    '// 统计抽屉状态': '// Stats drawer state',
    '// 分页和搜索状态': '// Pagination and search state',
    '// 模态框状态': '// Modal state',
    '// 表单状态': '// Form state',
    '// 获取计划列表': '// Fetch plan list',
    '// 处理创建计划': '// Handle create plan',
    '// 处理更新计划': '// Handle update plan',
    '// 处理删除计划': '// Handle delete plan',
    '// 打开编辑模态框': '// Open edit modal',
    '// 创建计划对话框': '// Create plan dialog',
    '// 编辑计划对话框': '// Edit plan dialog',
    '// 获取用户列表': '// Fetch user list',
    '// 获取所有计划列表（用于编辑用户时选择计划）': '// Fetch all plans (for plan selection when editing users)',
    '// 处理创建用户': '// Handle create user',
    '// 处理表单输入变化': '// Handle form input change',
    '// 处理复选框变化': '// Handle checkbox change',
    '// 处理计划选择变化': '// Handle plan selection change',
    '// 处理编辑表单提交': '// Handle edit form submit',
    '// 关闭编辑模态框': '// Close edit modal',
    '// 只有当密码字段有值时才包含密码': '// Only include password if field has a value',
    '// 编辑Modal相关状态': '// Edit modal state',
    '// 创建用户对话框': '// Create user dialog',
    '// 编辑用户对话框': '// Edit user dialog',
    '// 端点列表页': '// Endpoint list page',
    '// 多选状态': '// Multi-select state',
    '// 新增状态变量': '// New state variables',
    '// 测试状态管理': '// Test state management',
    '// 获取端点列表': '// Fetch endpoint list',
    '// 处理选择变化': '// Handle selection change',
    '// 处理批量测试端点': '// Handle batch test endpoints',
    '// 处理批量删除端点': '// Handle batch delete endpoints',
    '// 处理删除端点': '// Handle delete endpoint',
    '// 处理测试端点': '// Handle test endpoint',
    '// 直接调用函数式更新，避免 stale closure': '// Use functional update to avoid stale closure',
    '// 创建选择工具栏内容': '// Create selection toolbar content',
    '// 添加轮询逻辑': '// Add polling logic',
    '// 如果有正在测试的端点，开始轮询': '// Start polling if there are endpoints being tested',
    '// 创建一个当前ID列表的副本，用于闭包内部使用': '// Create a copy of current ID list for closure',
    '// 获取当前最新的测试ID列表': '// Get current latest test ID list',
    '// 检查每个正在测试的端点的状态': '// Check status of each endpoint being tested',
    '// 如果没有运行中的任务，从测试列表中移除': '// Remove from test list if no running tasks',
    '// 刷新端点列表以获取最新状态': '// Refresh endpoint list for latest status',
    '// 出错时也从列表中移除，避免无限尝试': '// Remove from list on error to avoid infinite retries',
    '// 更新正在测试的端点列表 - 使用函数式更新确保使用最新状态': '// Update testing endpoint list - use functional update for latest state',
    '// 如果没有正在测试的端点，清除轮询': '// Clear polling if no endpoints are being tested',
    '// 组件卸载时清除轮询': '// Clear polling on component unmount',
    '// 打开端点详情抽屉': '// Open endpoint detail drawer',
    '// 关闭端点详情抽屉': '// Close endpoint detail drawer',
    '// 创建端点对话框': '// Create endpoint dialog',
    '// 编辑端点对话框': '// Edit endpoint dialog',
    '// 端点详情抽屉': '// Endpoint detail drawer',
    '// 创建端点表单状态': '// Create endpoint form state',
    '// 批量创建端点表单状态': '// Batch create endpoint form state',
    '// 处理批量创建文本区域变化': '// Handle batch create textarea change',
    '// 处理创建端点表单提交': '// Handle create endpoint form submit',
    '// 确保 URL 格式正确': '// Ensure URL format is correct',
    '// 如果名称为空，使用 URL 作为名称': '// If name is empty, use URL as name',
    '// 提交创建请求': '// Submit create request',
    '// 创建成功，关闭模态框并刷新列表': '// Success, close modal and refresh list',
    '// 重置表单': '// Reset form',
    '// 表单验证': '// Form validation',
    '// 分割 URL 并过滤空行': '// Split URLs and filter empty lines',
    '// 处理批量创建': '// Handle batch create',
    '// 自动生成名称': '// Auto-generate name',
    '// 提交批量创建请求': '// Submit batch create request',
    '// 设置成功消息并清空表单': '// Set success message and clear form',
    '// 关闭模态框并重置表单': '// Close modal and reset form',
    '// 处理批量创建表单提交': '// Handle batch create form submit',
    '// 当 props 变化时更新表单数据': '// Update form data when props change',
    '// 关闭时重置状态': '// Reset state on close',
    '// 处理表单提交': '// Handle form submit',
    '// 提交更新请求': '// Submit update request',
    '// 更新成功，关闭模态框': '// Success, close modal',
    '// 获取端点详情': '// Fetch endpoint details',
    '// 在抽屉打开时重新获取数据': '// Refetch data when drawer opens',
    '// 获取端点状态': '// Get endpoint status',
    '// 格式化日期': '// Format date',
    '{/* 端点基本信息卡片 */}': '{/* Endpoint info card */}',
    '{/* AI 模型列表卡片 */}': '{/* AI model list card */}',
    '// 渲染抽屉内容': '// Render drawer content',
    '// 获取模型状态': '// Get model status',
    '// 获取模型详情': '// Get model details',
    '{/* 模型基本信息卡片 */}': '{/* Model info card */}',
    '{/* 可用端点列表卡片 */}': '{/* Available endpoints card */}',
    '// 获取API密钥使用统计': '// Fetch API key usage stats',
    '{/* API密钥使用统计卡片 */}': '{/* API key usage stats card */}',
    '{/* 每日请求图表卡片 */}': '{/* Daily requests chart card */}',
    '// 获取用户当前计划': '// Fetch user current plan',
    '{/* 管理员统计信息 */}': '{/* Admin statistics */}',
    '{/* 欢迎卡片 */}': '{/* Welcome card */}',
    '{/* 统计卡片 */}': '{/* Statistics cards */}',
    '{/* 主内容区域 */}': '{/* Main content area */}',
    '{/* 导航栏 */}': '{/* Navbar */}',
    '// 大屏幕下显示的主题切换开关': '// Theme toggle for large screens',
    '// 小屏幕下显示的主题切换选项': '// Theme toggle for small screens',
    '{/* 用户菜单 */}': '{/* User Menu */}',
    '// 主题切换组件': '// Theme toggle component',
    '// 获取表头列': '// Get header columns',
    '// 最小页面大小': '// Minimum page size',
    '// 最大页面大小': '// Maximum page size',
    '// 多选相关属性': '// Multi-select related props',
    '// 验证自定义页面大小的函数': '// Validate custom page size',
    '// 判断自定义页面大小是否无效': '// Check if custom page size is invalid',
    '// 处理自定义页面大小应用': '// Handle apply custom page size',
    '// 处理回车键应用自定义页面大小': '// Handle enter key for custom page size',
    '// 底部内容区域': '// Bottom content area',
    '// 顶部内容区域': '// Top content area',
    '// 不再需要处理"custom"选项，因为已经整合到下拉菜单中': '// No need to handle "custom" option, integrated into dropdown',
    '// 渲染表格': '// Render table',
    '// 主要渲染逻辑': '// Main render logic',
    '// 更新父组件中的排序状态': '// Update parent sort state',
    '// ChevronDownIcon组件': '// ChevronDownIcon component',
    '// 列定义类型': '// Column definition types',
    '// 添加按钮属性类型': '// Add button property types',
    '// DataTable组件属性类型': '// DataTable component property types',
    '// 通用DataTable组件': '// Generic DataTable component',
    '// 每页行数': '// Rows per page',
    '// 自定义页面大小': '// Custom page size',
    '// 根据状态类型设置颜色': '// Set color based on status type',
    '// 处理基本字段排序': '// Handle field sorting',
    '// 处理页码变化': '// Handle page change',
}

def translate_file(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    
    # First apply comment translations (exact line matches, longer first)
    sorted_comments = sorted(comment_translations.items(), key=lambda x: len(x[0]), reverse=True)
    for chinese, english in sorted_comments:
        content = content.replace(chinese, english)
    
    # Then apply UI string translations (longer first to avoid partial matches)
    sorted_translations = sorted(translations.items(), key=lambda x: len(x[0]), reverse=True)
    for chinese, english in sorted_translations:
        content = content.replace(chinese, english)
    
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        return True
    return False

# Process all frontend files
count = 0
for root, dirs, files in os.walk('frontend/src'):
    for f in files:
        if f.endswith(('.tsx', '.ts')):
            path = os.path.join(root, f)
            if translate_file(path):
                count += 1
                print(f'Translated: {path}')

print(f'\nTotal files translated: {count}')
